### PR TITLE
FdoServer: drop bubble reference when `destroy()` is emitted

### PR DESCRIPTION
**Pull request by Marukesu**
our bubble map was keeping a reference to the bubble, stoping it from being destroyed. drop our reference when `destroy()` is emitted.

Fixes: #212.

### CODE REVIEW

**Comment by leolost2605** [comment]
Thanks for the quick response :)
I think with the updates to #211 we won't need this anymore but if you want to keep it as a failsave I'm happy to approve

**Comment by Marukesu** [comment]
i perfer to revert #211 back to the approved state, the changes done there will make `close_notification()` throw for notifications in the tray.

**Comment by leolost2605** [comment]
Oh man I'm starting to loose track 😅. I reverted the changes there

**Review by leolost2605 — CHANGES_REQUESTED** [review]
Looks good but [this line](https://github.com/elementary/notifications/blob/8702ac2f5ca32ffc8bae4257ad903284d4bb2cab/src/DBus.vala#L154C30-L154C30) could probably also use a `null` check

**Comment by Marukesu** [comment]
Good catch! Added the null check.

**Review by leolost2605 — APPROVED** [review]
LGTM 🎉

**Pull request merged**
