### PR TITLE
Don't expire notifications when the timeout expires

### LINKED ISSUE #104: Notifications are closed automatically with reason expired
In elementary OS, Notifications are closed as expired (reasonclosed=1) when disappearing from the screen while still undismissed/waiting for action in the message area.  When writing applications which use notifications to inform users of new events and respond to input from user actions this is a problem.  It appears to the application like the user has dismissed the notification or cleared the message tray, which can cause a flood of notifications to replace it.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/52589907-notifications-are-closed-automatically-with-reason-expired?utm_campaign=plugin&utm_content=tracker%2F62872462&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F62872462&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #212: Invisible notification blocking input
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
Not sure when exactly but at some point an invisible window stays probably where the notification was. It's noticeable as it blocks interaction with e.g. wingpanel indicators or windows in this area. Killing notifications removes the window.

### To Reproduce
1. Get a notification 
2. Suspend
3. Wake up again
4. Open the session indicator and try to click a button
5. Notice inputs don't go through
6. For completeness: I had the fix-expiring branch applied

### Expected behavior
Don't keep a invisible window

### Logs
<details><summary>Details</summary>
<p>
That's the beginning and from there on it just kept repeating only the Source didn't show up again

```
(io.elementary.notifications:37353): GLib-CRITICAL **: 23:06:05.217: Source ID 515 was not found when attempting to remove it

(io.elementary.notifications:37353): Gtk-CRITICAL **: 23:06:05.217: gtk_widget_show_all: assertion 'GTK_IS_WIDGET (widget)' failed

(io.elementary.notifications:37353): Gtk-CRITICAL **: 23:06:20.633: gtk_widget_get_window: assertion 'GTK_IS_WIDGET (widget)' failed

(io.elementary.notifications:37353): Gtk-CRITICAL **: 23:06:20.633: gtk_widget_translate_coordinates: assertion 'GTK_IS_WIDGET (dest_widget)' failed

(io.elementary.notifications:37353): Gtk-CRITICAL **: 23:06:20.634: gtk_widget_get_settings: assertion 'GTK_IS_WIDGET (widget)' failed

(io.elementary.notifications:37353): GLib-GObject-CRITICAL **: 23:06:20.634: g_object_get: assertion 'G_IS_OBJECT (object)' failed

(io.elementary.notifications:37353): Gtk-CRITICAL **: 23:06:20.634: gtk_widget_get_window: assertion 'GTK_IS_WIDGET (widget)' failed

(io.elementary.notifications:37353): Gtk-CRITICAL **: 23:06:20.634: gtk_widget_translate_coordinates: assertion 'GTK_IS_WIDGET (dest_widget)' failed

(io.elementary.notifications:37353): Gtk-CRITICAL **: 23:06:20.634: gtk_widget_get_window: assertion 'GTK_IS_WIDGET (widget)' failed

(io.elementary.notifications:37353): Gtk-CRITICAL **: 23:06:20.634: gtk_widget_translate_coordinates: assertion 'GTK_IS_WIDGET (dest_widget)' failed

(io.elementary.notifications:37353): Gtk-CRITICAL **: 23:06:20.634: gtk_widget_get_settings: assertion 'GTK_IS_WIDGET (widget)' failed

(io.elementary.notifications:37353): GLib-GObject-CRITICAL **: 23:06:20.634: g_object_get: assertion 'G_IS_OBJECT (object)' failed

(io.elementary.notifications:37353): Gtk-CRITICAL **: 23:06:20.634: gtk_widget_get_window: assertion 'GTK_IS_WIDGET (widget)' failed

(io.elementary.notifications:37353): Gtk-CRITICAL **: 23:06:20.634: gtk_widget_translate_coordinates: assertion 'GTK_IS_WIDGET (dest_widget)' failed

(io.elementary.notifications:37353): Gtk-CRITICAL **: 23:06:20.634: gtk_widget_get_window: assertion 'GTK_IS_WIDGET (widget)' failed

(io.elementary.notifications:37353): Gtk-CRITICAL **: 23:06:20.634: gtk_widget_translate_coordinates: assertion 'GTK_IS_WIDGET (dest_widget)' failed

(io.elementary.notifications:37353): Gtk-CRITICAL **: 23:06:20.754: gtk_widget_get_window: assertion 'GTK_IS_WIDGET (widget)' failed

(io.elementary.notifications:37353): Gtk-CRITICAL **: 23:06:20.754: gtk_widget_translate_coordinates: assertion 'GTK_IS_WIDGET (dest_widget)' failed

(io.elementary.notifications:37353): Gtk-CRITICAL **: 23:06:20.754: gtk_widget_get_window: assertion 'GTK_IS_WIDGET (widget)' failed

(io.elementary.notifications:37353): Gtk-CRITICAL **: 23:06:20.754: gtk_widget_translate_coordinates: assertion 'GTK_IS_WIDGET (dest_widget)' failed

(io.elementary.notifications:37353): Gtk-CRITICAL **: 23:06:20.754: gtk_widget_get_window: assertion 'GTK_IS_WIDGET (widget)' failed

(io.elementary.notifications:37353): Gtk-CRITICAL **: 23:06:20.754: gtk_widget_get_window: assertion 'GTK_IS_WIDGET (widget)' failed

(io.elementary.notifications:37353): Gtk-CRITICAL **: 23:06:20.754: gtk_widget_get_window: assertion 'GTK_IS_WIDGET (widget)' failed

(io.elementary.notifications:37353): Gtk-CRITICAL **: 23:06:21.213: gtk_widget_get_window: assertion 'GTK_IS_WIDGET (widget)' failed

(io.elementary.notifications:37353): Gtk-CRITICAL **: 23:06:21.214: gtk_widget_translate_coordinates: assertion 'GTK_IS_WIDGET (dest_widget)' failed

(io.elementary.notifications:37353): Gtk-CRITICAL **: 23:06:21.214: gtk_widget_get_settings: assertion 'GTK_IS_WIDGET (widget)' failed

````

</p>
</details> 

## Platform Information

- [x] I'm using the latest version from git that I've manually compiled
- [ ] I'm using the latest released stable version

### PR DESCRIPTION
**Pull request by leolost2605**
We only close the window but don't send the `notification_closed` signal. That's because they are still visible in the notifications indicator and can still receive input/responses especially with elementary/wingpanel-indicator-notifications#263.

Fixes #104 
Closes #212

### CODE REVIEW

**Comment by Marukesu** [comment]
i would like to restore the expiration feature in the future, so a simpler way to remove the expiration now is to remove [src/DBus.vala:156](https://github.com/elementary/notifications/blob/361dbd22023d4904391b793d7dfb9e4e9c08d408/src/DBus.vala#L156).

**Comment by leolost2605** [comment]
But wouldn't that also prevent the signal from clicking the close button to be emitted?

**Comment by leolost2605** [comment]
@Marukesu nice, I updated it accordingly!

**Review by Marukesu — DISMISSED** [review]
Sorry the delay in the review. works as expected.

**Comment by leolost2605** [comment]
Causes #212

**Comment by danirabbit** [comment]
@leolost2605 can you resolve conflicts here?

**Comment by leolost2605** [comment]
@danirabbit done.

**Comment by danirabbit** [comment]
@Marukesu Do you still approve here? :)

**Review by danirabbit — APPROVED** [review]

**Pull request merged**
