### PR TITLE
Play different sound when notification is urgent

### PR DESCRIPTION
**Pull request by meisenzahl**
Related to https://github.com/elementary/notifications/issues/75

Works in conjunction with https://github.com/elementary/sound-theme/pull/11

Test with `io.elementary.notifications.demo` and set **Priority** to **Urgent**.

### CODE REVIEW

**Comment by meisenzahl** [comment]
@marbetschar, @danrabbit and @cassidyjames I would appreciate your feedback

**Comment by marbetschar** [comment]
@meisenzahl your PR does not play a sound at all on my end for URGENT notifications - but it does for regular ones. Is this the intended behaviour?

Tested it on elementary Daily (Pre-Release of Odin) using Time Limit [which sends a notification with `NotificationPriority.URGENT`](https://github.com/marbetschar/time-limit/blob/bf9506874aab928d79c2c2ce83d4875b9cb03572/src/Widgets/Clock.vala#L166-L170) once the time is up.

**Comment by meisenzahl** [comment]
@marbetschar I'm sorry I forget to mention that this feature only works in combination with https://github.com/elementary/sound-theme/pull/11 🙈

https://github.com/elementary/sound-theme/pull/11 provides a new sound for urgent notifications.

**Comment by marbetschar** [comment]
@meisenzahl installed your `sound-theme` branch, but still got no sound on elementary Daily. I tried logout/login and a reboot - but in both cases despite the Time Limit notification is shown, no sound is played.

**Comment by meisenzahl** [comment]
@marbetschar thanks for testing it again.

I just created a demo application to make testing easier. Please give this a try.

**Comment by meisenzahl** [comment]
Screenshot of the demo application to test the notifications server:

Screenshot von 2020-10-24 11 04 12

**Comment by marbetschar** [comment]
@meisenzahl thanks, but unfortunately still no success. Neither for Time Limit nor for the new notifications demo application. For both cases I can't hear any sound for the notification priority "URGENT". For all other notifications, the default sound is still played. Even a reboot did not help. Also, I double checked and the file `/usr/share/sounds/elementary/stereo/dialog-urgent.ogg` exists on my laptop and I'm able to play it using the Music app - so something else seems to be wrong here.

Maybe @danrabbit can help out?

**Comment by meisenzahl** [comment]
@marbetschar after a long time I tried it again after a new installation. Here it works. Does it work for you now?

**Review by marbetschar — APPROVED** [review]
Works for me, so its a :+1: from my end. Maybe someone from @elementary/ux wants review this as well before we merge it.

**Pull request merged**
