### PR TITLE
Release 7.0.0

### PR DESCRIPTION
**Pull request by lenemter**

### CODE REVIEW

**Comment by danirabbit** [comment]
Maybe we should hold this for a second to review some of Maru's branches? 

#202 seems to fix a few issues
#201 seems ready to go as well

**Comment by lenemter** [comment]
@danirabbit The release is not super urgent, I'm fine with waiting for these branches.

**Comment by lenemter** [comment]
@danirabbit Marukesu's branches are merged. Can we release this now?

**Comment by Marukesu** [comment]
i would really like if #189 could be in the release too, since that fixes the issue with urgent notifications not bypassing do not disturb.

**Review by danirabbit — APPROVED** [review]
Let's gooo :rocket:

**Pull request merged**
