### PR TITLE
Fix #117: Show icons for daemons

### LINKED ISSUE #117: Icon not set when notified from background process
## Prerequisites

- [x] I have searched open and closed issues for duplicates.

## Describe the bug

The notification server does not use the application icon when the notification is [sent from a daemon process](https://github.com/marbetschar/time-limit/blob/daemon/daemon/Daemon.vala):

Screenshot from 2021-05-04 23-29-30

## Expected behavior

The notification server should use the `Icon` defined in the `*.desktop` file of the daemon application.

## Possible root cause

The deamon is a `GLib.Application` with a *.desktop file stored in `/etc/xdg/autostart/com.github.marbetschar.time-limit-daemon.desktop`. It contains the following configuration:

```
[Desktop Entry]
Name=Time Limit Daemon
Comment=Notify when time is up
Exec=/usr/libexec/com.github.marbetschar.time-limit-daemon
Icon=com.github.marbetschar.time-limit
Terminal=false
Type=Application
Categories=System;
OnlyShowIn=Pantheon;
NoDisplay=true
X-GNOME-AutoRestart=true
X-GNOME-Autostart-Phase=Applications
X-GNOME-UsesNotifications=true
```

From what I understood, [the notification server uses the `DesktopAppInfo` to retrieve the `app_icon`](https://github.com/elementary/notifications/blob/eec89e611b3ea3976b377c700faa77f16f433e87/src/Notification.vala#L89-L95).

Furthermore the `DesktopAppInfo` itself uses the `app_id` to retrieve the desktop configuration file. And - [according to the docs](https://valadoc.org/gio-unix-2.0/GLib.DesktopAppInfo.DesktopAppInfo.html) - reads the path information from the `XDG_DATA_HOME` and `XDG_DATA_DIRS` environment variables:

> GIO is looking for a desktop file with this name in the `applications` subdirectories of the XDG data directories (i.e. the directories specified in the `XDG_DATA_HOME` and `XDG_DATA_DIRS` environment variables). GIO also supports the prefix-to-subdirectory mapping that is described in the Menu Spec (i.e. a desktop id of kde-foo.desktop will match `/usr/share/applications/kde/foo.desktop`).

However, If I print those environment variables the `/etc/xdg/autostart` directory does not appear. If I'm on the right track, this causes the notification icon of daemon apps to be never shown:

```
$ echo $XDG_DATA_HOME

$ echo $XDG_DATA_DIRS
/usr/share/gnome:/usr/share/pantheon:/home/$USER/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/
```

## Platform Information

elementary OS 6 Odin Daily.

### PR DESCRIPTION
**Pull request by marbetschar**
This PR adds a code change which loads a *.desktop file from `/etc/xdg/autostart` if available. This is needed for daemon processes which are automatically started in the background and are sending notifications to the user.

**Notification displayed before change**

Screenshot from 2021-05-04 23-29-30

**Notification displayed after change**

Screenshot from 2021-05-06 08-11-02

### CODE REVIEW

**Review by meisenzahl — APPROVED** [review]
Looks good and works as expected. Tested with `time-limit`

**Comment by davidmhewitt** [comment]
Please revert this. We shouldn't be loading desktop files from the autostart folder. This folder is *only* for desktop files that should be launched with the session (and they don't even need to be fully formed desktop files). Hence why this isn't in the standard lookup path for `DesktopAppInfo`.

If something (a daemon or otherwise) wants to send notifications, it should install a desktop file to an XDG applications path (e.g. `/usr/share/applications`). If it should be hidden from the applications menu because it's a daemon, use the `NoDisplay` key.

**Comment by marbetschar** [comment]
@davidmhewitt what about having the daemon autostarted? If I understand this correctly the desktop file of the daemon is placed in `/usr/share/applications` and we are creating a symlink to this file which is stored in `/etc/xdg/autostart` - right?

**Comment by danrabbit** [comment]
I'm not sure that apps can add their desktop files to auto start anymore. It looks like there is an interface in the background portal to request this: https://flatpak.github.io/xdg-desktop-portal/portal-docs.html#gdbus-org.freedesktop.impl.portal.Background

**Pull request merged**
