### PR TITLE
Support Actions

### LINKED ISSUE #1: Implement default_action
Clicking a notification should launch the action name set via the default action property of GLib.Notification: https://valadoc.org/gio-2.0/GLib.Notification.set_default_action.html

### PR DESCRIPTION
**Pull request by danrabbit**
Fixes #1

### CODE REVIEW

**Comment by donadigo** [comment]
Something isn't right here:
notification

The labels are flipped with the action ID's and the layout is kind of screwed.

**Comment by danrabbit** [comment]
Screenshot from 2019-06-16 20 23 24@2x

I guess we have to figure out what to do about this ^

**Comment by bluesabre** [comment]
@danrabbit I hacked on this a bit today, and I've got the actions working on top of the latest master.
https://github.com/bluesabre/notifications/tree/actions

I've made the following additional changes:
- Made the close button revealer only use the space in the corner to make the default and action buttons clickable again.
- Switched to just using the notification actions, which should make them behave as expected for the sending applications.
- Enabled action support for notifications without app_info.

Let me know if you'd like me to make any additional changes or to continue working on this.

**Comment by danrabbit** [comment]
@bluesabre Yes if you can propose that PR that would be great to move forward on this :)

**Comment by bluesabre** [comment]
> @bluesabre Yes if you can propose that PR that would be great to move forward on this :)

Awesome. Opened up a PR for the actions branch here: https://github.com/elementary/notifications/pull/125

**Comment by bluesabre** [comment]
@danrabbit Everything looks good to me, thanks!

**Pull request merged**
